CC=g++
FLAGS=-Wall -Wextra -Wswitch -Wconversion -Wparentheses -Wfloat-equal -Wzero-as-null-pointer-constant -Wpedantic -pedantic -pedantic-errors
SRCFILES=tictactoe.cpp main.cpp
OUTFILE=tictactoe
default:
	$(CC) $(FLAGS) -o $(OUTFILE) $(SRCFILES)
clean:
	rm -rf $(OUTFILE)
